#!/bin/bash

read -r -d '' message << EOM
===================:: Oh my zsh :: =====================
Do you wish to install zsh and oh my zsh?

EOM


while :
do
    echo "$message"
    echo
    read -p  "Enter [yn]:  " ans


    case $ans in
        [yY]* ) sudo pacman -S --noconfirm zsh ;

                sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" ;
                s_alias="alias s=sudo" ; 
                echo $s_alias >> $HOME/.zshrc ;
                source $HOME/.zshrc; exit;;
                    
        [nN]* ) exit ;;
        *) echo "Enter y|n correctly!" ;;
    esac
done

