[programming]
code
nano
nvim & lazyvim
anaconda*



[jetbrains-- *Still not included]
goland
intellij
pycharm


[man pages]
bropages
tldr


[container & virtualization]
docker
qemu
virtualbox


[language]
python
rust
golang
zsh


[utility]
bat
curl
htop
gzip
neofetch
tar
tcpdump
tree
wget
wireshark
yakuake
git
gh


[media]
ktorrent
okular


[browser]
brave-browser
firefox


[social]
discord
telegram



