[programming]
code
intellij
goland
git


[jetbrains]
goland
inetllij
pycharm

[man pages]
bropages


[conteiner]
docker
kubernetes



[vm]
virtualbox
qemu



[language]
rust
golang
zsh


[utility]
bat
curl
htop
gzip
neofetch
tar
tcpdump
tree
wget
wireshark
yakuake


[media]
ktorrent
okular


[browser]
brave-browser


[social]
discord
telegram
zoom



