#!/bin/bash

message=$(cat << EOF
===================:: Browser :: =====================
Which browser wish to install? 

        Firefox [1]
        Brave   [2]
        Both    [3]
        None    [4]
EOF
)

brave="sudo curl -fsSLo /usr/share/keyrings/brave-browser-archive-keyring.gpg https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg"
brave_="sudo apt update
        sudo apt install -y brave-browser"
while :
do
    echo "$message"
    echo
    read -p  "Enter 1|2|3|4: " ans

    case $ans in
        1 ) sudo apt -y install firefox-esr; exit ;;
        2 ) eval $brave; 
            echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
            eval $brave_; exit ;;
        
        3 ) sudo apt -y install firefox-esr;
            eval $brave; 
            echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"|sudo tee /etc/apt/sources.list.d/brave-browser-release.list
            eval $brave_;
            exit;;
        4 ) exit;;
        *) echo "Enter y|n correctly!" ;;
    esac
done





















