#!/bin/bash

message=$(cat << EOF
===================:: IDE's and Code Editor :: =====================
Following packages will be installed:
        
        vim                  [1]
        nano                 [2]
        vs-code              [3]
        
        -- all               [4]
        -- none              [5]
         
EOF
)

vs_code1="curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
sudo install -o root -g root -m 644 microsoft.gpg /usr/share/keyrings/microsoft-archive-keyring.gpg
"

vs_code2="sudo apt-get install apt-transport-https
          sudo apt-get update
          sudo apt-get install code"
         
while :
do
    echo "$message"
    echo
    read -p "Which package want to install? 1|2|3|4|5:   " ans

    case $ans in
        1 ) sudo apt -y install vim; exit;;
        2 ) sudo apt -y install nano; exit;;
        3 ) eval $vs_code1; 
            sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
            eval $vs_code2;
            exit;;
        
        4 ) sudo apt -y install vim;
            sudo apt -y install nano;
            eval $vs_code1; 
            sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
            eval $vs_code2; exit;;
        
        5 ) exit ;;
        *) echo "Enter 1|2|3|4|5 correctly!" ;;
    esac
done

