#!/bin/bash

read -r -d '' message << EOM
===================:: IDE's and Code Editor :: =====================
Following packages will be installed:
        
        vim                  [1]
        nano                 [2]
        vs-code              [3]
        
        -- all               [4]
        -- none              [5]
         
EOM

         
         
while :
do
    echo "$message"
    echo
    read -p "Which package want to install? 1|2|3|4|5:   " ans

    case $ans in
        1 ) sudo dnf -y install vim; exit;;
        2 ) sudo dnf -y install nano; exit;;
        3 ) sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc;
            sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo';
            sudo dnf check-update;
            sudo dnf install -y code; exit;;
        
        4 ) sudo dnf -y install vim;
            sudo dnf -y install nano;
            sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc;
            sudo sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo';
            sudo dnf check-update;
            sudo dnf install -y code; exit;;
        
        5 ) exit ;;
        *) echo "Enter 1|2|3|4|5 correctly!" ;;
    esac
done

