#!/bin/bash


<< 'cmnt'
Index:
        [1] Utilities
        [2] FlatHub or snap
        [3] Git Setup
        [4] Browsers
        [5] Social
        [6] Virtualization & Container
        [7] CodeSpaces & IDE
        [8] Programming Languages
        [9] Man page alternatives
        [10] NVIM & Lazyvim
        [11] Oh my zsh
        [12] Anaconda

cmnt


cp rcfiles/.bashrc $HOME/
cp rcfiles/.zshrc $HOME/

mkdir temp
curr_dir=$(pwd)


sh utilities                     # [1]
#sh flathub snap                 # [2]
sh github-setup                  # [3]
sh browsers                      # [4]
sh social                        # [5]
sh virtualization                # [6]
sh code_editors                  # [7]
sh prog_languages                # [8]
sh man_alternatives              # [9]
sh lazyvim                       # [10]
sh oh_my_zsh_setup               # [11]
sh anaconda                      # [12]

rm -rf $curr_dir/temp/