#!/bin/bash

message=$(cat << EOM
===================:: Social Packages :: =====================
Which Package want to install?

    Telegram          [1]   
    Discord           [2]
        
        --all         [3]
        --none        [4]
EOM
)

while :
do
    echo "$message"
    echo
    read -p "Enter 1|2|3|4   " ans

    case $ans in
        1 ) sudo apt install -y telegram-desktop; exit;;
        2 ) wget "https://discord.com/api/download?platform=linux&format=deb" -O discord.deb;
            sudo apt install -y ./discord.deb; 
            rm discord.deb;
            exit;;
        3 ) sudo apt install -y telegram-desktop; 
            wget "https://discord.com/api/download?platform=linux&format=deb" -O discord.deb;
            sudo apt install -y ./discord.deb; 
            rm discord.deb; exit;;
        4 ) exit;;

        *) echo "Enter y|n correctly!" ;;
    esac
done

