#!/bin/bash

message=$(cat << EOM
===================:: Container And Virtualization :: =====================
Which Package want to install?
    
    Docker              [1]     
    Virtualbox          [2]
    Qemu                [3]

        --all           [4]
        --none          [5]
         
EOM
)


curr_dir=$(pwd)
docker="sudo apt remove -y docker docker-engine docker.io containerd runc
        sudo apt update -y
        sudo apt install -y ca-certificates curl gnupg  lsb-release
        sudo mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg 
        echo 'deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable' | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update -y
        sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin"

vbox="  sudo apt -y install curl wget gnupg2 lsb-release
        curl -fsSL https://www.virtualbox.org/download/oracle_vbox_2016.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/oracle_vbox_2016.gpg
        curl -fsSL https://www.virtualbox.org/download/oracle_vbox.asc | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/oracle_vbox.gpg
        echo 'deb [arch=amd64] http://download.virtualbox.org/virtualbox/debian $(lsb_release -cs) contrib' | sudo tee /etc/apt/sources.list.d/virtualbox.list
        sudo apt update -y
        sudo apt install -y linux-headers-$(uname -r) dkms
        sudo apt install -y virtualbox-7.0"

while :
do
    echo "$message"
    echo
    read -p "Enter 1|2|3|4|5::   " ans

    case $ans in
        1 ) eval $docker; exit;;
        2 ) eval $vbox; exit;;
        3 ) sudo apt install -y qemu; exit;;
        4 ) eval $vbox; 
            eval $docker;
            sudo apt install -y qemu; exit;;
        5 ) exit;;

        *) echo "Enter 1|2|3|4|5 correctly!" ;;
    esac
done

